spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.gbgqvfsyhozxulbxlati
spring.datasource.password=dsadbms@7749

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=yourVerySecretKeyYourVerySecretKey12345
jwt.expiration=900000

cloudinary.cloud-name=dgtllm76i
cloudinary.api-key=752635597278918
cloudinary.api-secret=75y_Krv0sPOgfyhNJDNabBTm_i4