spring.datasource.url=jdbc:mysql://localhost:3306/cityfix
spring.datasource.username=root
spring.datasource.password=Sumit@2511
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=yourVerySecretKeyYourVerySecretKey12345
jwt.expiration=900000

cloudinary.cloud-name=dgtllm76i
cloudinary.api-key=752635597278918
cloudinary.api-secret=75y_Krv0sPOgfyhNJDNabBTm_i4